### ISSUE TITLE
Make pause button/back button work when it is the computer's turn

### ISSUE THREAD

**Issue by breber** [breber/cardgames#11]
When it is the computer's turn, it is really hard to click back (to end the game), or pause.  I think this is because of the sleeping the computers do to make it seem more like a human.  I wonder if that should be done on another thread or something.

**Comment by j7peters** [comment]
I thought that it was? I made it a separate activity. I don't know how to make it a separate thread.

**Comment by breber** [comment]
I will look into this...

**Comment by breber** [comment]
This should be fixed.  Let me know if you notice any problems this causes.
