### ISSUE TITLE
Euchre Rules Text

### ISSUE THREAD

**Issue by j7peters** [breber/cardgames#26]
We need to write rules for Euchre and then change a line in gamefactory to use the rules string resource.

**Comment by breber** [comment]
I am going to publish the update with Euchre now, but this still needs to be done.  We will publish a .1 upgrade when we finish this issue.

**Comment by j7peters** [comment]
I finished it. Brian I will leave the update publishing to you. Thanks.

**Comment by breber** [comment]
Update has been published. Thanks!
