### ISSUE TITLE
Choose different font

### ISSUE THREAD

**Issue by breber** [breber/cardgames#3]
Helsinki is missing a ton of characters (including the % sign which is necessary if we want to support IPv6 addresses).  Also, a font that has lowercase letters would be nice so that long blocks of text aren't a challenge to read.

**Comment by j7peters** [comment]
We should do this soon, because I was planning on using whatever font we chose to make the cards. so I will wait till we decide font before I finish the cards. I agree that we should switch fonts to one that has all characters. I am going to look at the fonts tonight.
