### ISSUE TITLE
Suggested Card to play

### ISSUE THREAD

**Issue by j7peters** [breber/cardgames#30]
Add a setting in the player settings page to have the game suggest which card would be good to play.  This should be implemented by adding a "suggested card" to the json message sent to the player.

**Comment by breber** [comment]
Can this be closed?

**Comment by j7peters** [comment]
yep, closed.

On Sat, Dec 22, 2012 at 1:01 PM, Brian Reber notifications@github.comwrote:

> Can this be closed?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/breber/CardGames/issues/30#issuecomment-11640184.

## 

Thanks,
Josh Peters
j7peters@gmail.com
