### ISSUE TITLE
Make CardTranslator Static

### ISSUE THREAD

**Issue by j7peters** [breber/cardgames#33]
I think we could make this static and just have a unique ID for each card that is consistent across games

**Comment by breber** [comment]
I sort of like how we handled this in the iOS branch.

**Comment by j7peters** [comment]
how was that done?

On Fri, Jan 18, 2013 at 12:40 PM, Brian Reber notifications@github.comwrote:

> I sort of like how we handled this in the iOS branch.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/breber/CardGames/issues/33#issuecomment-12435349.

## 

Thanks,
Josh Peters
j7peters@gmail.com

**Comment by breber** [comment]
I think we had a method in the Card class called getResourceId that returns the right resource based on the card's id.
